# Lineare Algebra in der Systemtheorie

Dieses Notebook liegt bereit um Mathematik Probleme mit Symbolen zu lösen. Dieses Notebook liegt bereit um Mathematik Probleme zu lösen mit Symbolen. Man braucht ein Python Umgebung um dieses Code zu laufen. Die Konzepten, die hier präsentiert sind, sind nur ein klein Teil von alle den Sachen die Mann mit Python machen kann.

In [2]:
import sympy as sp
import numpy as np

### Beispiel 1: Symbolische Lösungen

Für Matrix $\boldsymbol{A} = \begin{bmatrix} 1 & 1 & 0 \\ 1 & 2 & 1 \\ 0 & 1 & 1 \end{bmatrix}$ und Vektor $\boldsymbol{b} = \begin{bmatrix} 0 & 0 & 0 \end{bmatrix}^{\top}$ bestimmen Sie $\boldsymbol{x}$ in $\boldsymbol{A}\boldsymbol{x} = \boldsymbol{b}$. 

Hierzu verwenden wir die Funktion sp.linsolve() von Sympy, die ein „EmptySet“ zurückgibt, wenn das System inkonsistent ist (keine Lösung). 

Wir nehmen dann $\boldsymbol{x} = \begin{bmatrix}x_1 & x_2 & x_3\end{bmatrix}^{\top}$.

In [ ]:
# Definieren Sie Matrix A
A = sp.Matrix([
    [1, 1, 0],
    [1, 2, 1],
    [0, 1, 1]
])

# Definieren Sie die Variablen von x
x1, x2, x3 = sp.symbols('x1 x2 x3')

# Right-hand side vector
b = sp.Matrix([0, 0, 0])

# Solve the system A * x = B
solution = sp.linsolve((A, b), (x1, x2, x3))

print("Lösung für das System:")
solution

Lösung für das System:


{(x3, -x3, x3)}

### Beispiel 2: Exponentialmatrix

In Quiz 1 von unserem Kurs steht das folgende Problem:

Berechnen Sie die Matrix-Exponentialfunktion $\exp(\boldsymbol{A}t)$  mit der folgenden Matrix $\boldsymbol{A} = \begin{bmatrix} -2 & 3 \\ 1 & -4 \end{bmatrix}$.

Mit Sympy die Lösung ist trivial, mann muss einfach die Exponentialfunktion .exp() für die Multiplikation $\boldsymbol{A} t$ berechnen.

In [19]:
# Definieren Sie ein Matrix A
A = sp.Matrix([[-2, 3],
                [1, -4]])

# Definieren Sie eine Variable t
t = sp.symbols('t')

# Berechnen Sie die Matrixexponentialfunktion exp(At)
exp_At = (A * t).exp()

print(f"\nexp(At):")
exp_At 


exp(At):


Matrix([
[3*exp(-t)/4 + exp(-5*t)/4, 3*exp(-t)/4 - 3*exp(-5*t)/4],
[  exp(-t)/4 - exp(-5*t)/4,   exp(-t)/4 + 3*exp(-5*t)/4]])

### Beispiel 3: Beobachtungsnormalform

Von Übung 8, Aufgabe 2a) wir finden:

Gegeben sei ein lineares System mit
$$
\begin{aligned}
	\boldsymbol{A} & =\left[\begin{array}{ll}
		-2 & 4 \\
		-2 & 0
	\end{array}\right] & \boldsymbol{B} & =\left[\begin{array}{l}
		2 \\
		10
	\end{array}\right] \\
	\boldsymbol{C} & =\left[\begin{array}{ll}
		1 & 0
	\end{array}\right] & d & =0
\end{aligned}
$$

Bestimmen Sie die Transformation $\boldsymbol{T}$ mit $\boldsymbol{z}=\boldsymbol{T} \boldsymbol{x}$, so dass die Dynamik von $\boldsymbol{z}$ in Beobachtungsnormalform ist.

In [29]:
import numpy as np

# Definieren Sie die Matrizen A, B und c
A = np.array([[-2, 4],
                [-2, 0]])
b = np.array([[2],
                [10]])
c = np.array([1, 0]) # Achtung c ist ein Zeilenvektor

en = np.array([[0], [1]])

# Berechnen Sie die Beobachtbarkeitsmatrix Po
Po = np.array([c, np.matmul(c, A)])
print("Beobachtbarkeitsmatrix Po:\n", Po)

# Berechnen Sie die Inverse der Beobachtbarkeitsmatrix Po
Po_inv = np.linalg.inv(Po)
print("Inverse der Beobachtbarkeitsmatrix Po_inv:\n", Po_inv)

# Berechnen Sie den Vektor v
v = np.matmul(Po_inv, en)
print("Vektor v:\n", v)

# Berechnen Sie die Inverse von Transformation T
T_inv = np.hstack([v, A @ v])
print("Inverse von Transformationsmatrix:\n", T_inv)

# Berechnen Sie die Transformation T
T = np.linalg.inv(T_inv)
print("Transformationsmatrix T:\n", T)

# Berechnen Sie die Normalform der Matrizen A, B und c
A_normal = np.matmul(T, np.matmul(A, np.linalg.inv(T)))
print("Beobachtungsnormalform von A:\n", A_normal)

B_normal = np.matmul(T, b)
print("Beobachtungsnormalform von b:\n", B_normal)

c_normal = np.matmul(c, T_inv)
print("Beobachtungsnormalform von c:\n", c_normal)

Beobachtbarkeitsmatrix Po:
 [[ 1  0]
 [-2  4]]
Inverse der Beobachtbarkeitsmatrix Po_inv:
 [[ 1.   -0.  ]
 [ 0.5   0.25]]
Vektor v:
 [[0.  ]
 [0.25]]
Inverse von Transformationsmatrix:
 [[0.   1.  ]
 [0.25 0.  ]]
Transformationsmatrix T:
 [[0. 4.]
 [1. 0.]]
Beobachtungsnormalform von A:
 [[ 0. -8.]
 [ 1. -2.]]
Beobachtungsnormalform von b:
 [[40.]
 [ 2.]]
Beobachtungsnormalform von c:
 [0. 1.]


### Beispiel 4: Normalform mit Sympy

Von Übung 8, Aufgabe 3a) wir finden:

Für das Systems 
 $$
 \begin{aligned}
 	\dot{\boldsymbol{x}} & =\left[\begin{array}{ccc}
 		0 & -1 & -1 \\
 		-1.5 & 0.5 & -1.5 \\
 		0.5 & -0.5 & 1.5
 	\end{array}\right] \boldsymbol{x}+\left[\begin{array}{c}
 		(1+\alpha) / \sqrt{2} \\
 		0 \\
 		(-1+\alpha) / \sqrt{2}
 	\end{array}\right] u \\
 	y & =\left[\begin{array}{lll}
 		3 / \sqrt{2} & -1 / \sqrt{2} & 1 / \sqrt{2}
 	\end{array}\right] \boldsymbol{x}
 \end{aligned}
 $$
 mit $\alpha \in \mathbb{R}$ sei eine Zustandstransformation
  der Form
 $$
 x=\boldsymbol{T} z
 $$
 bekannt, wobei $z$ der transformierten Zustand ist. Die Transformationsmatrix $\boldsymbol{T}$ und ihre Inverse $\boldsymbol{T}^{-1}$ sind wie folgt gegeben:
 $$
 \boldsymbol{T}=\frac{1}{\sqrt{2}}\left[\begin{array}{ccc}
 	1 & 1 & 0 \\
 	1 & 0 & 1 \\
 	0 & -1 & -1
 \end{array}\right], \quad \boldsymbol{T}^{-1}=\frac{1}{\sqrt{2}}\left[\begin{array}{ccc}
 	1 & 1 & 1 \\
 	1 & -1 & -1 \\
 	-1 & 1 & -1
 \end{array}\right]
 $$

 Da wir eine symbolische Variable haben, müssen wir dieses Problem mit Sympy lösen.

In [ ]:
np.set_printoptions(suppress=True, precision=5) # Dies verhindert die wissenschaftliche Notation von kleine Zahlen

# Definieren Sie eine Symbole für alpha
alpha = sp.symbols('alpha')

# Definieren Sie die Matrizen A, b und c, T und Inverse von T für die Normalform
A = np.array([[0, -1, -1],
                [-1.5, 0.5, -1.5],
                [0.5, -0.5, 1.5]])

b = sp.Matrix([[(1 + alpha) / np.sqrt(2)],
                [0],
                [(-1 + alpha) / np.sqrt(2)]])

c = np.array([3/np.sqrt(2), -1/np.sqrt(2), 1/np.sqrt(2)])

T = (1 / np.sqrt(2)) * np.array([[1, 1, 0],
                    [1, 0, 1],
                    [0, -1, -1]])

T_inv = (1 / np.sqrt(2)) *np.array([[1, 1, 1],
                            [1, -1, -1],
                            [-1, 1, -1]])


# Berechnen Sie die Normalform der Matrizen A, b und c
A_normal = np.matmul(T_inv, np.matmul(A, T))
b_normal = np.matmul(T_inv, b)
c_normal = np.matmul(c, T)
print("Normal form of A:\n", A_normal)
print("Normal form of b:\n", b_normal)
print("Normal form of c:\n", c_normal)

Normal form of A:
 [[-1. -0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  2.]]
Normal form of b:
 [[1.0*alpha]
 [1.00000000000000]
 [-1.0*alpha]]
Normal form of c:
 [ 1.  1. -1.]
