# Lineare Algebra in der Systemtheorie

Es gibt zwei wichtige Python-Bibliotheken, die in diesem Kurs hilfreich sein können:

- **Sympy**: eine Bibliothek für symbolische Berechnungen.
- **Numpy**: die _de facto_ optimale Numerischebibliothek für Python.

Für mehr Information von jeder Bibliothek, ihr könnt die [Sympy](https://docs.sympy.org/latest/modules/matrices/matrices.html) oder [Numpy](https://numpy.org/doc/2.2/reference/routines.linalg.html) Webseiten besuchen.

Unser ersten Schritt ist beide Bibliotheken mit dem nächsten Befehl zu integrieren.

In [2]:
import sympy as sp
import numpy as np

### Beispiel 1: Symbolische Lösungen

Für Matrix $\boldsymbol{A} = \begin{bmatrix} 1 & 1 & 0 \\ 1 & 2 & 1 \\ 0 & 1 & 1 \end{bmatrix}$ und Vektor $\boldsymbol{b} = \begin{bmatrix} 0 & 0 & 0 \end{bmatrix}^{\top}$ bestimmen Sie $\boldsymbol{x}$ in $\boldsymbol{A}\boldsymbol{x} = \boldsymbol{b}$. 

Hierzu verwenden wir die Funktion sp.linsolve() von Sympy, die ein „EmptySet“ zurückgibt, wenn das System inkonsistent ist (keine Lösung).

In [10]:
x1, x2, x3 = sp.symbols('x1 x2 x3')

# Coefficient matrix A 
A = sp.Matrix([
    [1, 1, 0],
    [1, 2, 1],
    [0, 1, 1]
])

# Right-hand side vector
b = sp.Matrix([0, 0, 0])

# Solve the system A * x = B
solution = sp.linsolve((A, b), (x1, x2, x3))

print("Lösung für das System:")
solution

Lösung für das System:


{(x3, -x3, x3)}

### Beispiel 2: Eigenwerte und Eigenvektoren

Wir können auch **Eigenwerten** und **Eigenvektoren** finden mit den Funktionen eigenvals() und eigenvects().



In [ ]:
A = sp.Matrix([[-2, 3],
                [1, -4]])

t = sp.Symbol('t')

eigenvalues = A.eigenvals(multiple=True)
print(f"Eigenwerten: {eigenvalues[0]}, {eigenvalues[1]}\n")

eigenvektoren = A.eigenvects()
print("Eigenvektoren:")
for eigenvalue, multiplicity, eigvecs in eigenvektoren:
    print(f"Eigenwert: {eigenvalue}, Vielfachheit: {multiplicity}, Eigenvektoren: {eigvecs}")

exp_At = (A * t).exp()
print(f"\nexp(At):")
exp_At 

Eigenwerten: -5, -1

Eigenvektoren:
Eigenwert: -5, Vielfachheit: 1, Eigenvektoren: [Matrix([
[-1],
[ 1]])]
Eigenwert: -1, Vielfachheit: 1, Eigenvektoren: [Matrix([
[3],
[1]])]

exp(At):


Matrix([
[3*exp(-t)/4 + exp(-5*t)/4, 3*exp(-t)/4 - 3*exp(-5*t)/4],
[  exp(-t)/4 - exp(-5*t)/4,   exp(-t)/4 + 3*exp(-5*t)/4]])

In [5]:
import numpy as np
from numpy import linalg as LA

# Define the matrices and vectors
A = np.array([[-2, 4],
                [-2, 0]])
B = np.array([[2],
                [10]])
c = np.array([1, 0]) # careful, this is a column vector

en = np.array([[0], [1]]) # this is a row vector

# Form the observavbility matrix
Po = np.array([c, np.matmul(c, A)])
print("Observability matrix Po:\n", Po)

# Find the inverse of the observability matrix
Po_inv = LA.inv(Po)
print("Inverse of the observability matrix Po_inv:\n", Po_inv)

# Calculate the vector
v = np.matmul(Po_inv, en)
print("Vector v:\n", v)

# Form the transformation matrix T
T_inv = np.hstack([v, A @ v])
print("Inverse of the transformation matrix:\n", T_inv)

T = LA.inv(T_inv)
print("Transformation matrix T:\n", T)

A_normal = np.matmul(T, np.matmul(A, LA.inv(T)))
print("Normal form of A:\n", A_normal)

B_normal = np.matmul(T, B)
print("Normal form of B:\n", B_normal)

c_normal = np.matmul(c, T_inv)
print("Normal form of c:\n", c_normal)

T = np.array([[-10, 2],
                [16, -40]])
T_inv = np.array([[40, 2],
                [16, 10]])

print(LA.matmul(LA.matmul(T, A), T_inv))

Observability matrix Po:
 [[ 1  0]
 [-2  4]]
Inverse of the observability matrix Po_inv:
 [[ 1.   -0.  ]
 [ 0.5   0.25]]
Vector v:
 [[0.  ]
 [0.25]]
Inverse of the transformation matrix:
 [[0.   1.  ]
 [0.25 0.  ]]
Transformation matrix T:
 [[0. 4.]
 [1. 0.]]
Normal form of A:
 [[ 0. -8.]
 [ 1. -2.]]
Normal form of B:
 [[40.]
 [ 2.]]
Normal form of c:
 [0. 1.]
[[   0 -368]
 [2944  736]]


In [6]:
np.set_printoptions(suppress=True, precision=5) # This command avoids printing small numbers in scientific notation
alpha = sp.symbols('alpha')

A = np.array([[0, -1, -1],
                [-1.5, 0.5, -1.5],
                [0.5, -0.5, 1.5]])

b = sp.Matrix([[(1 + alpha) / np.sqrt(2)],
                [0],
                [(-1 + alpha) / np.sqrt(2)]])

c = np.array([3/np.sqrt(2), -1/np.sqrt(2), 1/np.sqrt(2)])

T = (1 / np.sqrt(2)) * np.array([[1, 1, 0],
                    [1, 0, 1],
                    [0, -1, -1]])

T_inv = (1 / np.sqrt(2)) *np.array([[1, 1, 1],
                            [1, -1, -1],
                            [-1, 1, -1]])



A_normal = np.matmul(T_inv, np.matmul(A, T))
b_normal = np.matmul(T_inv, b)
c_normal = np.matmul(c, T)
print("Normal form of A:\n", A_normal)
print("Normal form of b:\n", b_normal)
print("Normal form of c:\n", c_normal)

Normal form of A:
 [[-1. -0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  2.]]
Normal form of b:
 [[1.0*alpha]
 [1.00000000000000]
 [-1.0*alpha]]
Normal form of c:
 [ 1.  1. -1.]


In [22]:
t = sp.Symbol('t')
A = sp.Matrix([[-1, 0, 0],
                [0, -2, 0],
                [0, 0, -3]])

alpha0 = 2*sp.exp(-1*t) + sp.exp(-3*t) - 2*sp.exp(-2*t) + sp.exp(-1*t)
print(alpha0)
alpha1 = sp.exp(-1*t) + ((3 / 2) * (sp.exp(-3*t) - 2 * sp.exp(-2*t) + sp.exp(-1*t))) - sp.exp(-2*t)
print(alpha1)
alpha2 = (1 / 2) * (sp.exp(-3*t) - 2 * sp.exp(-2*t) + sp.exp(-1*t))
print(alpha2)

exp_At = sp.eye(3) * alpha0 + A * alpha1 + (A * A) * alpha2
exp_At

3*exp(-t) - 2*exp(-2*t) + exp(-3*t)
2.5*exp(-t) - 4.0*exp(-2*t) + 1.5*exp(-3*t)
0.5*exp(-t) - 1.0*exp(-2*t) + 0.5*exp(-3*t)


Matrix([
[1.0*exp(-t) + 1.0*exp(-2*t),             0,                             0],
[                          0, 2.0*exp(-2*t),                             0],
[                          0,             0, 1.0*exp(-2*t) + 1.0*exp(-3*t)]])