# Linear Algebra in System Theory

In [1]:
import sympy as sp

Solve a $A\vec{x} = \vec{b}$ problem. 

For this we use the sp.linsolve() function of sympy, which returns an 'EmptySet' if the system is inconsistent (no solution).

In [4]:
c1, c2, c3 = sp.symbols('c1 c2 c3')

# Coefficient matrix A 
A = sp.Matrix([
    [1, 1, 0],
    [1, 2, 1],
    [0, 1, 1]
])

# Right-hand side vector (homogeneous case)
B = sp.Matrix([0, 0, 0])

# Solve the system A * [x, y] = B
solution = sp.linsolve((A, B), (c1, c2, c3))

print("Solution to the system:", solution)

Solution to the system: {(c3, -c3, c3)}


In [21]:
import sympy as sp

A = sp.Matrix([[-2, 3],
                [1, -4]])
t = sp.Symbol('t')
eigenvalues = A.eigenvals(multiple=True)
print(f"Eigenvalues: {eigenvalues[0]}, {eigenvalues[1]}\n")

exp_At = (A * t).exp()
print(f"exp(At): {exp_At}\n")

Eigenvalues: -5, -1

exp(At): Matrix([[3*exp(-t)/4 + exp(-5*t)/4, 3*exp(-t)/4 - 3*exp(-5*t)/4], [exp(-t)/4 - exp(-5*t)/4, exp(-t)/4 + 3*exp(-5*t)/4]])



In [15]:
import numpy as np
from numpy import linalg as LA

# Define the matrices and vectors
A = np.array([[-2, 4],
                [-2, 0]])
B = np.array([[2],
                [10]])
c = np.array([1, 0]) # careful, this is a column vector

en = np.array([[0], [1]]) # this is a row vector

# Form the observavbility matrix
Po = np.array([c, np.matmul(c, A)])
print("Observability matrix Po:\n", Po)

# Find the inverse of the observability matrix
Po_inv = LA.inv(Po)
print("Inverse of the observability matrix Po_inv:\n", Po_inv)

# Calculate the vector
v = np.matmul(Po_inv, en)
print("Vector v:\n", v)

# Form the transformation matrix T
T_inv = np.hstack([v, A @ v])
print("Inverse of the transformation matrix:\n", T_inv)

T = LA.inv(T_inv)
print("Transformation matrix T:\n", T)

A_normal = np.matmul(T, np.matmul(A, LA.inv(T)))
print("Normal form of A:\n", A_normal)

B_normal = np.matmul(T, B)
print("Normal form of B:\n", B_normal)

c_normal = np.matmul(c, T_inv)
print("Normal form of c:\n", c_normal)

T = np.array([[-10, 2],
                [16, -40]])
T_inv = np.array([[40, 2],
                [16, 10]])

print(LA.matmul(LA.matmul(T, A), T_inv))

Observability matrix Po:
 [[ 1  0]
 [-2  4]]
Inverse of the observability matrix Po_inv:
 [[ 1.   -0.  ]
 [ 0.5   0.25]]
Vector v:
 [[0.  ]
 [0.25]]
Inverse of the transformation matrix:
 [[0.   1.  ]
 [0.25 0.  ]]
Transformation matrix T:
 [[0. 4.]
 [1. 0.]]
Normal form of A:
 [[ 0. -8.]
 [ 1. -2.]]
Normal form of B:
 [[40.]
 [ 2.]]
Normal form of c:
 [0. 1.]
[[   0 -368]
 [2944  736]]
